fastlane_version "2.205.2"

default_platform(:ios)

lane :beta do
#     FASTLANE_TEAM_ID=33ZJ787XV5
    update_code_signing_settings(
          use_automatic_signing: true,
          path: "iosHyperskillApp.xcodeproj",
    )

    clear_derived_data
    cocoapods(repo_update: true)

    gym(
        configuration: "Debug",
        clean: true,
        output_directory: "artifacts",
        include_bitcode: false,
        skip_profile_detection: true,
        export_method: "ad-hoc",
    )
end
