android:
  - 'androidHyperskillApp/**'
  - 'gradle/app.versions.toml'
shared:
  - 'shared/**'
ios:
  - 'iosHyperskillApp/**'
analytic:
  - 'shared/**/analytic/**'
  - '.github/workflows/gh_pages_analytics.yml'