shared:
- changed-files:
  - any-glob-to-any-file: shared/**

ios:
- changed-files:
  - any-glob-to-any-file: iosHyperskillApp/**

android:
- changed-files:
  - any-glob-to-any-file: androidHyperskillApp/**

ci/cd:
- changed-files:
  - any-glob-to-any-file: ['.github/workflows/**', '.github/actions/**', '.github/dependabot.yml', '.github/filters.yaml', '.github/labeler.yml']