shared:
  - shared/**

ios:
  - iosHyperskillApp/**

android:
  - androidHyperskillApp/**

ci/cd:
  - .github/workflows/**
  - .github/actions/**
  - .github/dependabot.yml
  - .github/filters.yaml
  - .github/labeler.yml