package org.hyperskill.app.notification.click_handling.injection

import org.hyperskill.app.notification.click_handling.presentation.NotificationClickHandlingActionDispatcher
import org.hyperskill.app.notification.click_handling.presentation.NotificationClickHandlingReducer

interface NotificationClickHandlingComponent {
    val notificationClickHandlingReducer: NotificationClickHandlingReducer
    val notificationClickHandlingActionDispatcher: NotificationClickHandlingActionDispatcher
}