warning_threshold: 15

indentation: 4

disabled_rules:
  - redundant_discardable_let
  - function_body_length
  - inclusive_language
  - cyclomatic_complexity
  - type_body_length
  - superfluous_disable_command

opt_in_rules:
  - empty_count
  - array_init
  - attributes
  - closure_end_indentation
  - closure_spacing
  - collection_alignment
  - comma_inheritance
  - conditional_returns_on_newline
  - contains_over_filter_count
  - contains_over_filter_is_empty
  - contains_over_first_not_nil
  - contains_over_range_nil_comparison
  - convenience_type
  - discarded_notification_center_observer
  - discouraged_assert
  - discouraged_none_name
  - discouraged_object_literal
  - discouraged_optional_boolean
  - empty_collection_literal
  - empty_count
  - empty_string
  - enum_case_associated_values_count
  - fallthrough
  - fatal_error_message
  - file_header
  - file_name_no_space
  - final_test_case
  - first_where
  - flatmap_over_map_reduce
  - force_unwrapping
  - identical_operands
  - implicit_return
  - implicitly_unwrapped_optional
  - inert_defer
  - joined_default_parameter
  - last_where
  - legacy_multiple
  - let_var_whitespace
  - literal_expression_end_indentation
  - local_doc_comment
  - lower_acl_than_parent
  - modifier_order
  - multiline_arguments
  - multiline_arguments_brackets
  - multiline_literal_brackets
  - multiline_parameters
  - multiline_parameters_brackets
  - nslocalizedstring_key
  - operator_usage_whitespace
  - optional_enum_case_matching
  - overridden_super_call
  - override_in_extension
  - prefer_zero_over_explicit_init
  - prohibited_interface_builder
  - prohibited_super_call
  - raw_value_for_camel_cased_codable_enum
  - reduce_into
  - redundant_nil_coalescing
  - redundant_self_in_closure
  - redundant_type_annotation
  - shorthand_optional_binding
  - sorted_first_last
  - sorted_imports
  - static_operator
  - switch_case_on_newline
  - toggle_bool
  - unavailable_function
  - unhandled_throwing_task
  - unowned_variable_capture
  - unused_capture_list
  - vertical_whitespace_closing_braces
  - vertical_whitespace_opening_braces
  - weak_delegate
  - yoda_condition

analyzer_rules:
  - unused_declaration
  - unused_import

excluded:
  - iosHyperskillApp/Sources/Frameworks/sharedSwift/Hyperskill-Mobile_shared.swift
  - iosHyperskillApp/Sources/Frameworks/sharedSwift/Extensions/**/*.swift

# settings
attributes:
  severity: error
  attributes_with_arguments_always_on_line_above: false

identifier_name:
  severity: error
  excluded:
    ["i", "j", "x", "y", "z", "id", "to", "vk", "h1", "h2", "h3", "r", "g", "b", "no", "ok", "c", "cs", "go", "js"]
  max_length: 64

large_tuple:
  warning: 3
  error: 3

type_name:
  min_length: 3
  max_length:
    warning: 64
    error: 64
  allowed_symbols: ["_"]

file_length:
  warning: 400
  error: 400
  ignore_comment_only_lines: true

file_header:
  forbidden_pattern: "^//[^/]|/\\*[^*]"

line_length:
  warning: 120
  error: 200
  ignores_urls: true
  ignores_comments: true
  ignores_interpolated_strings: true

nesting:
  type_level: 3

unused_import:
  require_explicit_imports: true
  allowed_transitive_imports:
    - module: Foundation
      allowed_transitive_imports:
        - CoreFoundation
        - Darwin
        - ObjectiveC
