source "https://rubygems.org"
ruby "3.3.0"

gem "fastlane", "2.219.0"
gem "cocoapods", "1.15.0"
gem "generamba", git: "https://github.com/ivan-magda/Generamba.git", branch: "develop"

eval_gemfile("fastlane/Pluginfile")