source "https://rubygems.org"
ruby "3.1.0"

gem "fastlane", "2.216.0"
gem "cocoapods", "1.13.0"
gem "generamba", git: "https://github.com/ivan-magda/Generamba.git", branch: "develop"

eval_gemfile("fastlane/Pluginfile")