source "https://rubygems.org"
ruby "3.3.0"

gem "fastlane", "2.227.0"
gem "cocoapods", "1.16.2"
gem "generamba", git: "https://github.com/ivan-magda/Generamba.git", branch: "develop"

eval_gemfile("fastlane/Pluginfile")
