install! "cocoapods", :deterministic_uuids => false
source "https://cdn.cocoapods.org/"

inhibit_all_warnings!
use_frameworks!

target "iosHyperskillApp" do
  platform :ios, "14.0"

  pod "shared", :path => "../shared"

  pod "SwiftLint", "0.50.1"
  pod "Sentry", "8.0.0"

  # Social SDKs
  pod "GoogleSignIn", "6.1.0"

  pod "IQKeyboardManagerSwift", "6.5.9"
  pod "SVProgressHUD", "2.2.5"
  pod "SkeletonUI", "1.0.9"

  pod "PanModal", :git => "https://github.com/ivan-magda/PanModal.git", :branch => "remove-presenting-appearance-transitions"
  pod "CombineSchedulers", :git => "https://github.com/ivan-magda/combine-schedulers.git", :branch => "main"

  # ContentProcessor
  pod "Kanna", "5.2.7"
  pod "STRegex", "2.1.1"
  pod "SnapKit", "5.6.0"
  pod "Atributika", "4.10.1"

  # CodeEditor
  pod "Highlightr", :git => "https://github.com/raspu/Highlightr.git", :branch => "master"

  # LazyImage with SVG support
  pod "NukeUI", :git => "https://github.com/kean/NukeUI.git", :tag => "0.8.3"
  pod "SVGKit", :git => "https://github.com/SVGKit/SVGKit.git", :branch => "3.x"
end

post_install do |installer|
  installer.pods_project.targets.each do |target|
    target.build_configurations.each do |config|
      if config.build_settings["IPHONEOS_DEPLOYMENT_TARGET"].to_f < 11.0
        config.build_settings["IPHONEOS_DEPLOYMENT_TARGET"] = "11.0"
      end
    end

    # Fix Xcode 14 bundle code signing issue
    if target.respond_to?(:product_type) and target.product_type == "com.apple.product-type.bundle"
      target.build_configurations.each do |config|
        config.build_settings["CODE_SIGNING_ALLOWED"] = "NO"
      end
    end
  end
end
