install! 'cocoapods', :deterministic_uuids => false
source 'https://github.com/CocoaPods/Specs.git'

inhibit_all_warnings!
use_frameworks!

target 'iosHyperskillApp' do
  platform :ios, '14.1'

  pod 'shared', :path => '../shared'

  pod 'SwiftLint', '0.47.0'
  pod 'Sentry', '7.13.0'

  pod 'GoogleSignIn', '6.1.0'

  pod 'IQKeyboardManagerSwift', '6.5.9'
  pod 'SVProgressHUD', '2.2.5'
  
  pod 'SkeletonUI', '1.0.7'
end

post_install do |installer|
  installer.pods_project.targets.each do |target|
    target.build_configurations.each do |config|
      if config.build_settings['IPHONEOS_DEPLOYMENT_TARGET'].to_f < 9.0
        config.build_settings['IPHONEOS_DEPLOYMENT_TARGET'] = '9.0'
      end
    end
  end
end
