name: Deploy to Firebase App Distribution

on:
  workflow_call:

jobs:
  deploy:
    runs-on: ubuntu-22.04
    environment: android_production
    timeout-minutes: 30

    steps:
      - name: Checkout
        uses: actions/checkout@v4.2.0

      - name: Setup CI
        id: setup
        uses: ./.github/actions/setup-android
        with:
          git-crypt-key: ${{ secrets.GIT_CRYPT_KEY }}
          release-keystore-content: ${{ secrets.HYPERSKILL_RELEASE_KEYSTORE_CONTENT }}
          setup-ruby: true

      - name: Submit a new Beta Build to Firebase App Distribution
        working-directory: "./androidHyperskillApp"
        run: |
          bundle exec fastlane beta \
            firebase_app_id:"${{ secrets.FIREBASE_APP_ID }}" \
            firebase_cli_token:"${{ secrets.FIREBASE_TOKEN }}"
        env:
          HYPERSKILL_IS_INTERNAL_TESTING: true
          HYPERSKILL_KEYSTORE_PATH: ${{ steps.setup.outputs.release-keystore-path }}
          HYPERSKILL_RELEASE_STORE_PASSWORD: ${{ secrets.HYPERSKILL_RELEASE_STORE_PASSWORD }}
          HYPERSKILL_RELEASE_KEY_ALIAS: ${{ secrets.HYPERSKILL_RELEASE_KEY_ALIAS }}
          HYPERSKILL_RELEASE_KEY_PASSWORD: ${{ secrets.HYPERSKILL_RELEASE_KEY_PASSWORD }}
          IS_GIT_CRYPT_UNLOCKED: ${{ steps.setup.outputs.is-git-crypt-unlocked }}
          GITHUB_USER: ${{ github.actor }}
          GITHUB_PERSONAL_ACCESS_TOKEN: ${{ secrets.GITHUB_TOKEN }}
