name: Build

on:
  pull_request:
    types: [opened, synchronize, reopened]
    branches:
      - 'feature/**'
      - 'dependabot/bundler/**'
  push:
    branches:
      - 'feature/**'
      - 'dependabot/bundler/**'
  workflow_dispatch:

concurrency:
  group: ${{ github.workflow }}-${{ github.ref_name }}
  cancel-in-progress: true

defaults:
  run:
    shell: bash

jobs:
  files-changed:
    name: Detect what files changed
    uses: ./.github/workflows/detect_changed_files_reusable_workflow.yml

  build-android:
    needs: files-changed
    if: ${{ needs.files-changed.outputs.android == 'true' || needs.files-changed.outputs.shared == 'true' }}
    name: Build Android
    runs-on: ubuntu-22.04
    timeout-minutes: 60

    steps:
    - name: Checkout
      uses: actions/checkout@v3.3.0

    - name: Setup CI
      id: setup
      uses: ./.github/actions/setup-android
      with:
        git-crypt-key: ${{ secrets.GIT_CRYPT_KEY }}

    - name: Build
      run: ./gradlew assembleDebug
      env:
        IS_GIT_CRYPT_UNLOCKED: ${{ steps.setup.outputs.is-git-crypt-unlocked }}
        GITHUB_USER: ${{ github.actor }}
        GITHUB_PERSONAL_ACCESS_TOKEN: ${{ secrets.GITHUB_TOKEN }}
  
  build-ios:
    needs: files-changed
    if: ${{ needs.files-changed.outputs.ios == 'true' || needs.files-changed.outputs.shared == 'true' }}
    name: Build iOS
    runs-on: macos-12
    timeout-minutes: 60
    
    steps:
      - name: Checkout
        uses: actions/checkout@v3.3.0

      - name: Setup CI
        id: setup
        uses: ./.github/actions/setup-ios
        with:
          git-crypt-key: ${{ secrets.GIT_CRYPT_KEY }}

      - name: Build
        working-directory: './iosHyperskillApp'
        run: bundle exec fastlane build install_pods:false
        env:
          FASTLANE_XCODEBUILD_SETTINGS_TIMEOUT: 60
          IS_GIT_CRYPT_UNLOCKED: ${{ steps.setup.outputs.is-git-crypt-unlocked }}
          GITHUB_USER: ${{ github.actor }}
          GITHUB_PERSONAL_ACCESS_TOKEN: ${{ secrets.GITHUB_TOKEN }}