name: Feature Branch Fastlane

on:
  push:
    branches:
      - 'feature/*'

jobs:
  Fastlane:
    runs-on: macos-latest
    steps:
      - uses: actions/checkout@v2

      - uses: ruby/setup-ruby@v1
        with:
          ruby-version: '2.7.6'

      - name: Run Fastlane
        uses: maierj/fastlane-action@v2.2.0
        with:
          lane: beta
          subdirectory: iosHyperskillApp
          verbose: true
