name: Feature Branch Fastlane
on:
  push:
    branches:
      - 'feature/*'
jobs:
  build:
    runs-on: macos-latest
    steps:
      - uses: actions/checkout@v3
      - run: bundle exec fastlane beta
        env:
          FASTLANE_TEAM_ID: 33ZJ787XV5
