name: Build and Deploy Analytics Documentation to GitHub Pages

on:
  push:
    branches:
      - 'main'
  workflow_dispatch:

# Sets permissions of the GITHUB_TOKEN to allow deployment to GitHub Pages
permissions:
  contents: read
  pages: write
  id-token: write

concurrency:
  group: ${{ github.workflow }}
  cancel-in-progress: true

jobs:
  build:
    runs-on: ubuntu-22.04
    timeout-minutes: 10

    steps:
      - name: Checkout
        uses: actions/checkout@v3.2.0

      - name: Setup CI
        uses: ./.github/actions/setup-android

      - name: Setup Pages
        uses: actions/configure-pages@v2.1.3

      - name: Build Documentation
        run: ./gradlew dokkaAnalytics
        env:
          GITHUB_USER: ${{ github.actor }}
          GITHUB_PERSONAL_ACCESS_TOKEN: ${{ secrets.GITHUB_TOKEN }}

      - name: Upload Artifact
        uses: actions/upload-pages-artifact@v1.0.7
        with:
          name: 'github-pages-analytics'
          path: 'shared/build/dokka/analytics'

  deploy:
    needs: build
    runs-on: ubuntu-22.04
    timeout-minutes: 10

    environment:
      name: github_pages_analytics
      url: ${{ steps.deployment.outputs.page_url }}
    
    steps:
      - name: Deploy to GitHub Pages
        id: deployment
        uses: actions/deploy-pages@v1.2.3
        with:
          artifact_name: 'github-pages-analytics'